name: build and release to PyPI

on:
  release:
    types:
      - released

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: (github.repository == 'astropy/repo_stats')

    steps:
      - name: Check out repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
        with:
          python-version: 3.11

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install setuptools wheel twine
          pip install pep517 --user

      - name: Install package
        run: |
          pip install .

      - name: Build binary wheel and source tarball
        run: |
          python -m pep517.build --source --binary --out-dir dist/ .

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33  # v1.14.2
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
